name: PaidPortals
version: '${project.version}'
main: me.maurxce.paidportals.PaidPortals
api-version: 1.19
authors: [ maurxce ]
description: Use Economy to unlock dimensions!
website: https://schorn.md/
depend: [ Vault ]
softdepend: [ PlaceholderAPI ]

commands:
  paidportals:
    description: Command to access PaidPortals
    usage: /<command>
    aliases: [ pp ]

permissions:
  paidportals.use:
    description: Permission to access the `/paidportals` command
    default: true

  paidportals.pay:
    description: Permission to access the `/paidportals pay` command
    default: true

  paidportals.balance:
    description: Permission to access the `/paidportals balance` command
    default: true

  paidportals.goal:
    description: Permission to access the `/paidportals goal` command
    default: true

  paidportals.reload:
    description: Permission to access the `/paidportals reload` command
    default: op

  paidportals.reset:
    description: Permission to access the `/paidportals reset` command
    default: op

  paidportals.ignore:
    description: Allows players to use portals even when it's locked for normal players
    default: op